# Generated by Django 3.0.7 on 2020-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('github', models.CharField(max_length=150, verbose_name='GitHub')),
                ('linkedin', models.CharField(max_length=150, verbose_name='LinkedINn')),
                ('instagram', models.CharField(max_length=150, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=150, verbose_name='Facebook')),
            ],
        ),
    ]
